<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="1.36"/>
    <xacro:property name="chassis_width" value="1.17"/>
    <xacro:property name="chassis_height" value="1.17"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.26"/>
    <xacro:property name="wheel_thickness" value="0.13"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.26"/>
    <xacro:property name="wheel_offset_y" value="0.13"/>
    <xacro:property name="wheel_offset_z" value="0.26"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${(chassis_height/2)}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="-${chassis_length/4} -${chassis_width/8} -${(chassis_height/2) - wheel_offset_z}" rpy="${pi/2} 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://gazebo_viz/meshes/body.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.1"/>
            <geometry>
                <box size="${chassis_length/2} ${chassis_width/2} ${chassis_height/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="20" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_back_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_back"/>
        <origin xyz="-${(chassis_length/4) + 0.085} ${chassis_width/2} ${(wheel_offset_z/2) + 0.02}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
        <mimic joint="left_wheel_front_joint" multiplier="1" offset="0" />
    </joint>

    <link name="left_wheel_back">
        <visual>
            <origin xyz="${0.061} -0.01 -0.1" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://gazebo_viz/meshes/wheel_left.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="left_wheel_front_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_front"/>
        <origin xyz="${(chassis_length/4) + 0.14} ${chassis_width/2} ${(wheel_offset_z/2) + 0.02}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_front">
        <visual>
            <origin xyz="${0.061} -0.01 -0.1" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://gazebo_viz/meshes/wheel_left.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_back_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_back"/>
        <origin xyz="-${(chassis_length/4) + 0.080} -${chassis_width/2 - 0.025} ${(wheel_offset_z/2) + 0.02}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
        <mimic joint="right_wheel_front_joint" multiplier="1" offset="0" />
    </joint>

    <link name="right_wheel_back">
        <visual>
            <origin xyz="${0.061} -0.01 -0.1" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://gazebo_viz/meshes/wheel_left.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="right_wheel_front_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_front"/>
        <origin xyz="${(chassis_length/4) + 0.14} -${chassis_width/2 - 0.025} ${(wheel_offset_z/2) + 0.02}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel_front">
        <visual>
            <origin xyz="${0.061} -0.01 -0.1" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://gazebo_viz/meshes/wheel_left.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>